config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "malibuitlabs.com"
  resources :enquiries, :except => [:index, :edit, :show, :edit, :update, :destroy]
  #get 'pages/index'
  root to: 'pages#index'
  devise_for :users
  resources :blogs, :except => [:latest_blogs]
  get 'latestblogs' => 'blogs#latest_blogs', :as => 'latest_blogs'
  get 'ourblog' => 'blogs#ourblog', :as => 'ourblog'
  get 'about-us' => 'pages#aboutus', :as => 'about-us'
  get 'portfolio' => 'pages#portfolio', :as => 'portfolio'
  get 'services' => 'pages#service', :as => 'services'
  get 'technologies' => 'pages#technologies', :as => 'technologies'
  get 'web-design' => 'pages#webdesign', :as => 'webdesign'
  get 'application-development' => 'pages#application_development', :as => 'application-development'
  get 'bigdata' => 'pages#bigdata', :as => 'bigdata'
  get 'data-warehousing-and-business-intelligence' => 'pages#data-warehousing-and-business-intelligence', :as => 'data-warehousing-and-business-intelligence'
  get 'data-and-information-management' => 'pages#data-and-information-management', :as => 'data-and-information-management'
  get 'cloud-and-infrastructure-service' => 'pages#cloud-and-infrastructure-service', :as => 'cloud-and-infrastructure-service'
  get 'qualityassurance' => 'pages#qualityassurance', :as => 'qualityassurance'
  get 'ecommerce' => 'pages#ecommerce', :as => 'ecommerce'
  get 'cms' => 'pages#cms', :as => 'cms'
  get 'mobile-app-dev' => 'pages#mobile-app-dev', :as => 'mobile-app-dev'
  get 'reactjs' => 'pages#reactjs', :as => 'reactjs'
  get 'nodejs' => 'pages#nodejs', :as => 'nodejs'

 
  #get 'careers' => 'pages#careers', :as => 'careers'
  get 'test' => 'pages#test', :as => 'test'
  get 'ecommerce/shopify' => 'pages#shopify', :as => 'ecommerce/shopify'
  get 'ecommerce/magento' => 'pages#magento', :as => 'ecommerce/magento'
  get 'ecommerce/woocommerce' => 'pages#woocommerce', :as => 'ecommerce/woocommerce'
  get 'ecommerce/upgrademagento' => 'pages#upgrademagento', :as => 'ecommerce/upgrademagento'
  get 'contact' => 'contact_pages#new', :as => 'contact_pages'
  post 'contact' => 'contact_pages#create'
  get 'our-privacy-policy' => 'pages#term&privacy', :as => 'our-privacy-policy'
  get 'careers' => 'careers#new', :as => 'careers'
  post 'careers' => 'careers#create'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
 extend FriendlyId
  friendly_id :title, use: :slugged
  scope :Reviews, -> { where(:category => "Reviews") }
scope :FAQ, -> { where(:category => "FAQ") }
scope :General, -> { where(:category => "General") }
scope :Quality, -> { where(:category => "Quality") }
scope :Other, -> { where(:category => "Other") }
scope :Payment, -> { where(:category => "Payment") }
scope :Shipping, -> { where(:category => "Shipping") }
scope :CancelReturn, -> { where(:category => "CancelReturn") }
has_many :blog_photos, dependent: :destroy


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  require 'benchmark'


		before_action :set_blog, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show, :index ]

def index

@blog = Blog.where( state: true ).paginate(:page => params[:page],  :per_page => 12).order('id DESC')


@blog_last = @blog.first

end
def ourblog

@blog = Blog.where( state: true ).paginate(:page => params[:page],  :per_page => 12).order('id DESC')

end

def latest_blogs
if current_user.admin?
@blog = Blog.paginate(:page => params[:page],  :per_page => 12).order('id DESC')
else
 flash[:error] = "you are not authorised to visit this section"
redirect_to root_path
end 

end 

def new
  @blog = Blog.new
end

 def show
 @blog_photos = @blog.blog_photos
 title = @blog.title
  
 keywords = title.split(/\W+/)
  set_meta_tags title: @blog.title,
            site: 'Telugol',
            reverse: true,
            description: @blog.description.gsub(/<.*?>/, ""), 
            keywords: keywords,
            current_url: request.url,
           # image: @blog.blog_photos.first.image_file_name,
           # refresh: 30,
               alternate: [
             { href: 'https://malibuitlabs.com/about'},
             { href: 'https://malibuitlabs.com/services'},
             { href: 'https://malibuitlabs.com/blogs'},
             { href: 'https://malibuitlabs.com/careers'},       
              ]
           
 
 end


  def create
  #  @blog = Blog.new(blog_params)
     @blog = current_user.blogs.build(blog_params)
    if @blog.save
      if params[:images]
        params[:images].each do |image|
          @blog.blog_photos.create(image: image)
        end
      end

      @blog_photos = @blog.blog_photos
      redirect_to edit_blog_path(@blog), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
     @blog_photos = @blog.blog_photos
  end

   def update
      if current_user.admin?
        if @blog.update(admin_blog_params)
        #redirect_to root_path, notice: "Updated..."
        redirect_to latest_blogs_path, notice: "Updated..."
        else
         render :edit
        end
      else  
        if @blog.update(blog_params)
          if params[:images]
            params[:images].each do |image|
            @blog.blog_photos.create(image: image)
            end
          end
          redirect_to blogs_path, notice: "Updated..."
          
        else
          render :edit
        end
      end
   end

  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
     format.html { redirect_to blogs_path }
     # format.json { head :no_content }
   end
 end

  


   
private
  def set_blog
    @blog = Blog.friendly.find(params[:id])

    
  end 

def blog_params
    params.require(:blog).permit( :title, :description, :category, :keywords, :user_id, :name)
end
def admin_blog_params
    params.require(:blog).permit( :title, :description, :category, :keywords, :user_id, :name, :state)
end



end

app/views/blogs/_blog.html.erb
<%= form_for(blog) do |f| %>
  	<td><%= f.label "active" %>
      	<%= f.check_box :state %>
  	</td>
    <td>
    	<%= f.submit 'Change', class: "btn-update" %>
    </td>
 
  <% end %>

app/views/blogs/_form.html.erb
<head>
<!--script src="/assets/jquery.js"></script>
<script src="/assets/jquery.cleditor.min.js"></script-->
 <%= javascript_include_tag "jquery.js" %>
  <%= javascript_include_tag "jquery.cleditor.min.js" %>

   <!--link rel="stylesheet" type="text/css" href="/assets/jquery.cleditor.css"-->
    <%= stylesheet_link_tag "jquery.cleditor.css" %>
   
  
   <script type="text/javascript"> 
     jQuery(document).ready(function ($) { 
        $("#input").cleditor(); 
      }); 
    </script> 
 </head> 

<div class="ro large-top">
  <div class="col-md-2">
    <%= render 'layouts/blogsidebar' %>
  </div>
  <div class="col-md-10 blogbackground">
    <div class="row">
      <div class="col-md-12">
        <h3>New Post/ Edit post</h3>
        <hr>
      </div>
    </div>
    <%= form_for @blog, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
      <div class="col-md-12">
        <div class="row">
          <!--div class="col-md-12">
            <label>Category</label>
              <div class="form-group">
                <!--%= f.select :category, [["",""], ["",""], ["",""],["",""],["Other","Other"],["",""],["", ""],["Cancellation and Returns", "CancelReturn"],], {id: 'category', prompt: 'Select...'},class: "form-control", :required => false %>
              </div>                  
          </div-->
            </div> 
         <!--%= f.hidden_field :user_id, value: current_user.id %-->  
         <!--%= f.hidden_field :name, value: current_user.name %-->
        <div class="row">
          <div class="col-md-12">
            <%= f.label :title, :class => 'control-label' %>
            <div class="form-group">
              <%= f.text_field :title, class: "form-control" %>
            </div>  
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= f.label :keywords, :class => 'control-label' %>
            <div class="form-group">
              <%= f.text_field :keywords, class: "form-control" %>
            </div>
          </div>  
        </div>  
        
        <div class="row">
          <div class="col-md-12">
            <%= f.label :description, :class => 'control-label' %>
            <div class="form-group">
              <%= f.cktext_area :description, id: "input", :class => 'ckeditor',ckeditor: {toolbar: 'mini'} %>

            </div>
          </div>  
        </div>
       
        

        <div class="row">
          <div class="col-md-12 amet-sed">
            <label>Upload Image</label>
            <div class="form-group">
              <span class="">
                  <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
                    <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>    
            </div>
          </div>  
        </div>

        <div class="row">
          <div class="col-md-12 amet-sed">
            <div class="form-group">
              <%= f.submit "Create", class: "btn btn-success" %>
            </div>  
          </div>
        </div>
      </div>    
    <% end %>
  </div>
</div>    

  

app/views/blogs/edit.html.erb
<style>
.mp-pusher{
		height:0px!important;
	}
</style>
<div class="container huge-top small-bottom">
	<%= render 'form' %>
</div>


app/views/blogs/index.html.erb
<style>
.mainHeading {
    font-size: 22px;
}
.newsDesc {
    font-size: 16px;
}
/*Cards*/

.row {
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
}

.cardAlignment {
    display: flex;
}

.card {
    background-color: #ffffff;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 40%;
    border-radius: 5px;
}

.mainCard {
    background-color: #ffffff;
    margin-top: 20px;
    margin-bottom: 20px;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 100%;
    border-radius: 5px;
}

.mainCard:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.newsImage {
    width: 100%;
    height: 250px !important;
    border-radius: 5px 5px 0 0;
}

.cardContainer {
		padding: 2px 16px;
}

/*Cards*/
</style>
		<div style="margin-top: 108px; margin-bottom: 50px">
				<div class="container">
          <div class="row">
						<% @blog.each do |blog| %>
						<div class="col-md-4 cardAlignment">
								<div class="mainCard">
				<% if blog.blog_photos.present?%>
						<%= image_tag blog.blog_photos[0].image.url,  class: "img-responsive newsImage" if blog.blog_photos.length > 0 %>
						 <%else%>
						   
				<%end%>
					<div class="cardContainer">
				<h2 class="mainHeading">
					 <%= link_to blog do%>

					<%=blog.title%></h2>

				 <%end%>
	
				<p class="newsDesc"><%= truncate(sanitize(blog.description, tags: []), length: 200) %></p>
				
		 <%= link_to blog ,{ :class=>"more-link" } do%>
<p class="newsDesc">
				Read this Post 
				</p>
		<%end%>
			




	</div>
</div>
</div>
<%end%>
</div>
</div>
</div>

app/views/blogs/latest_blogs.html.erb
<style>
	.thumb
	{
		width: 100px;
		height: 100px;
	}
	.latest-section
	{
		
		margin-bottom: 4em;
	}
	.latest-center
	{
		margin-top: 2em;
		margin-bottom: 2em;
		text-align: center;
	}
</style>
<div class="container latest-section">
	<div class="row">
		<div class="col-md-12">
			<h2 class="latest-center">Latest Blogs</h2>
		</div>
	</div>	
	<div class="row">	
		<div class="col-md-12">
			<div class="table-responsive">          
			  	<table class="table table-striped">
			    	<thead>
					    <tr>
					       <th>Post</th>
					       <th>Posted Date</th>
					       <th>Posted By</th>
					       <th>Title</th>
					       <th>Category</th>
					       <th colspan="3">Actions</th>
					       <th>Active/Inactive</th>
					    </tr>
			    	</thead>
			    	
				    	<tbody>
				    		<% @blog.each do |blog| %>
				      		<tr>
						        <td>
						        	<%= link_to blog do %>
						        		<%= image_tag blog.blog_photos[0].image.url, class: "thumb" if blog.blog_photos.length > 0 %>
						        	<% end %>	
						        </td>
						        <td><%= blog.created_at.to_time.strftime("%B %d, %Y") %></td>		
						        <% if blog.name.present? %>
						        <td>Posted By <%= blog.name %></td>
						        <% else %>
						        <td>Not Mentioned</td>
						        <% end %>
						        <td><%= blog.title %></td>
						        <td><%= blog.category %></td>
						        <td><%= link_to "Edit", edit_blog_path(blog), class: "info" %></td>
								<td><%= link_to 'Delete', blog_path(blog), :method => 'delete', data: {confirm: "Are you sure?"}, :class => 'info' %></td>
								<td><%= link_to "Qucik View", blog_path(blog), class: "info" %></td>

						        <%= render blog %>
				      		</tr>
				      		<% end %>
				    	</tbody>
			    	
			  	</table>
			</div>
		</div>
	</div>
</div>

app/views/blogs/new.html.erb
<style>
.site-main {
		margin-top: 104px;
	}
</style>
<div id="page" class="site">
	<div id="content" class="site-content">
		<div id="primary" class="content-area">
			<main id="main" class="site-main" role="main">
<div class="container">
	<%= render 'form' %>
</div>
</main>
</div>


app/views/blogs/ourblog.html.erb
<div class="smaple">
  <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="pageTitle heading-top-dist">Our Blog</h2>
            </div>
        </div>
    </div>
</div>
<div class="container huge-top small-bottom">
	<div class="row">
		<div class="col-md-8 col-sm-8">
			<div class="heads"><h2><b>Our Blog</b></h2></div>
			<% @blog.last(1).each do |blog| %>
				<div class="row">
					<div class="col-md-8 col-sm-8">
						<%= link_to blog do %>
							<div class="thumbnai">
								<div class="view view-eighth">
									<%= image_tag blog.blog_photos[0].image.url, class: "img-responsive" if blog.blog_photos.length > 0 %>
								</div>       
							</div>
						<% end %>
					</div>
					<div class="col-md-4 col-sm-4">
						<div class="truncate">
							<p><%= raw(blog.description) %></p>
						</div>	
						<div>
							<%= link_to "Read More...", blog_path(blog), class: "info" %>
						</div>
					</div>
				</div>	
				<div class="row">
					<div class="col-md-12">
						<div class="actions">
									<% if user_signed_in? %>
										<% if current_user.id == blog.user.id || current_user.admin? %>
											<%= link_to "Edit", edit_blog_path(blog), class: "info" %>
											<%= link_to 'Delete', blog_path(blog), :method => 'delete', data: {confirm: "Are you sure?"}, :class => 'info' %>
											<%= link_to "Qucik View", blog_path(blog), class: "info" %>
										<% else %>
											Posted By: Admin
										<% end %>
										
									<% end %>
								</div>	
					</div>
				</div>		
			<% end %>
		</div>
		<div class="col-md-4 col-sm-4">
		</div>
	</div>		
</div>		

app/views/blogs/show.html.erb
<style>
.popular-border{
  width: 1180px;
   height: 400px;
}
.mp-pusher{
    height:0px!important;
  }
span{
  color: #545454;
    font-size: 15px !important;
    line-height: 24px;
    font-family: !important; 
   background-color: #ffff!important;
color: #333333 !important; 
}
.content-area{
  margin-top: 100px;
}
.mp-pusher{
    height:0px!important;
  }
</style>
<div id="primary" class="content-area">
  <main id="main" class="site-main" role="main">
  <div class="header-last">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
           
          </div>
        </div>
      </div>
    </div>          

      
  <div class="container">
    <div class="row">
    <div class="col-md-12">
 
<article id="post-9329" class="post-9329 post type-post status-publish format-standard has-post-thumbnail hentry category-bigcommerce category-e-commerce category-web-development tag-age-verification-app-in-bigcommerce tag-age-verification-page tag-age-verification-pop-up tag-bigcommerce-age-verification-app tag-bigcommerce-app-development">
  <header class="entry-header">
    
  </header>
    
   <% if @blog_photos.present? %>

            <% @blog_photos.each do |blog_photo| %>
  <div class="post-thumbnail">

    <%= image_tag blog_photo.image.url(), class: "img-responsive popular-border"  %>
    
  
  </div><%end%>
   <%else%>
      
  <%end%><!-- .post-thumbnail -->

    <footer class="entry-footer">
    <span class="byline"><span class="author vcard"><span class="posted-on"><span class="screen-reader-text">Posted on </span> <time class="entry-date published" ><%= @blog.created_at.strftime("%D")%></time> </span><span class="cat-links">  </footer><!-- .entry-footer -->
  <div class="entry-content">
 
  <h1 class="entry-title"><%= @blog.title %></h1> 
  <p><%= raw(@blog.description)%></p>
  </div><!-- .entry-content -->

  
</article>
</div>
</div>
</div>