config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "malibuitlabs.com"
  resources :enquiries, :except => [:index, :edit, :show, :edit, :update, :destroy]
  #get 'pages/index'
  root to: 'pages#index'
  devise_for :users
  resources :blogs, :except => [:latest_blogs]
  get 'latestblogs' => 'blogs#latest_blogs', :as => 'latest_blogs'
  get 'ourblog' => 'blogs#ourblog', :as => 'ourblog'
  get 'about-us' => 'pages#aboutus', :as => 'about-us'
  get 'portfolio' => 'pages#portfolio', :as => 'portfolio'
  get 'services' => 'pages#service', :as => 'services'
  get 'technologies' => 'pages#technologies', :as => 'technologies'
  get 'web-design' => 'pages#webdesign', :as => 'webdesign'
  get 'application-development' => 'pages#application_development', :as => 'application-development'
  get 'bigdata' => 'pages#bigdata', :as => 'bigdata'
  get 'data-warehousing-and-business-intelligence' => 'pages#data-warehousing-and-business-intelligence', :as => 'data-warehousing-and-business-intelligence'
  get 'data-and-information-management' => 'pages#data-and-information-management', :as => 'data-and-information-management'
  get 'cloud-and-infrastructure-service' => 'pages#cloud-and-infrastructure-service', :as => 'cloud-and-infrastructure-service'
  get 'qualityassurance' => 'pages#qualityassurance', :as => 'qualityassurance'
  get 'ecommerce' => 'pages#ecommerce', :as => 'ecommerce'
  get 'cms' => 'pages#cms', :as => 'cms'
  get 'mobile-app-dev' => 'pages#mobile-app-dev', :as => 'mobile-app-dev'
  get 'reactjs' => 'pages#reactjs', :as => 'reactjs'
  get 'nodejs' => 'pages#nodejs', :as => 'nodejs'

 
  #get 'careers' => 'pages#careers', :as => 'careers'
  get 'test' => 'pages#test', :as => 'test'
  get 'ecommerce/shopify' => 'pages#shopify', :as => 'ecommerce/shopify'
  get 'ecommerce/magento' => 'pages#magento', :as => 'ecommerce/magento'
  get 'ecommerce/woocommerce' => 'pages#woocommerce', :as => 'ecommerce/woocommerce'
  get 'ecommerce/upgrademagento' => 'pages#upgrademagento', :as => 'ecommerce/upgrademagento'
  get 'contact' => 'contact_pages#new', :as => 'contact_pages'
  post 'contact' => 'contact_pages#create'
  get 'our-privacy-policy' => 'pages#term&privacy', :as => 'our-privacy-policy'
  get 'careers' => 'careers#new', :as => 'careers'
  post 'careers' => 'careers#create'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)
    
    respond_to do |format|
      if @enquiry.save
          flash[:notice]="we have recieved your details successfully"
          ContactMailer.enquery_email(@enquiry).deliver_now
        format.html { redirect_to root_path, notice: 'Enquiry was successfully created.' }

        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.permit(:first_name, :last_name, :email, :phonenumber, :message)
    end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<style>
                                #_form_5C7A37DA4E087_ { font-size:14px; line-height:1.6; font-family:arial, helvetica, sans-serif; margin:0; }
 #_form_5C7A37DA4E087_ * { outline:0; }
 ._form_hide { display:none; visibility:hidden; }
 ._form_show { display:block; visibility:visible; }
 #_form_5C7A37DA4E087_._form-top { top:0; }
 #_form_5C7A37DA4E087_._form-bottom { bottom:0; }
 #_form_5C7A37DA4E087_._form-left { left:0; }
 #_form_5C7A37DA4E087_._form-right { right:0; }
 #_form_5C7A37DA4E087_ input[type="text"],#_form_5C7A37DA4E087_ input[type="date"],#_form_5C7A37DA4E087_ textarea { padding:6px; height:auto; border:#979797 1px solid; border-radius:4px; color:#000 !important; font-size:13px; -webkit-box-sizing:border-box; -moz-box-sizing:border-box; box-sizing:border-box; }
 #_form_5C7A37DA4E087_ textarea { resize:none; }
 #_form_5C7A37DA4E087_ ._submit { -webkit-appearance:none; cursor:pointer; font-family:arial, sans-serif; font-size:14px; text-align:center; background:#f73 !important; border:0 !important; -moz-border-radius:4px !important; -webkit-border-radius:4px !important; border-radius:4px !important; color:#444 !important; padding:15px !important; }
 #_form_5C7A37DA4E087_ ._close-icon { cursor:pointer; background-image:url('https://d226aj4ao1t61q.cloudfront.net/esfkyjh1u_forms-close-dark.png'); background-repeat:no-repeat; background-size:14.2px 14.2px; position:absolute; display:block; top:11px; right:9px; overflow:hidden; width:16.2px; height:16.2px; }
 #_form_5C7A37DA4E087_ ._close-icon:before { position:relative; }
 #_form_5C7A37DA4E087_ ._form-body { margin-bottom:30px; }
 #_form_5C7A37DA4E087_ ._form-image-left { width:150px; float:left; }
 #_form_5C7A37DA4E087_ ._form-content-right { margin-left:164px; }
 #_form_5C7A37DA4E087_ ._form-branding { color:#fff; font-size:10px; clear:both; text-align:left; margin-top:30px; font-weight:100; }
 #_form_5C7A37DA4E087_ ._form-branding ._logo { display:block; width:130px; height:14px; margin-top:6px; background-image:url('https://d226aj4ao1t61q.cloudfront.net/hh9ujqgv5_aclogo_li.png'); background-size:130px auto; background-repeat:no-repeat; }
 #_form_5C7A37DA4E087_ ._form-label,#_form_5C7A37DA4E087_ ._form_element ._form-label { font-weight:bold; margin-bottom:5px; display:block; }
 #_form_5C7A37DA4E087_._dark ._form-branding { color:#333; }
 #_form_5C7A37DA4E087_._dark ._form-branding ._logo { background-image:url('https://d226aj4ao1t61q.cloudfront.net/jftq2c8s_aclogo_dk.png'); }
 #_form_5C7A37DA4E087_ ._form_element { position:relative; margin-bottom:10px; font-size:0; max-width:100%; }
 #_form_5C7A37DA4E087_ ._form_element * { font-size:14px; }
 #_form_5C7A37DA4E087_ ._form_element._clear { clear:both; width:100%; float:none; }
 #_form_5C7A37DA4E087_ ._form_element._clear:after { clear:left; }
 #_form_5C7A37DA4E087_ ._form_element input[type="text"],#_form_5C7A37DA4E087_ ._form_element input[type="date"],#_form_5C7A37DA4E087_ ._form_element select,#_form_5C7A37DA4E087_ ._form_element textarea:not(.g-recaptcha-response) { display:block; width:100%; -webkit-box-sizing:border-box; -moz-box-sizing:border-box; box-sizing:border-box; }
 #_form_5C7A37DA4E087_ ._field-wrapper { position:relative; }
 #_form_5C7A37DA4E087_ ._inline-style { float:left; }
 #_form_5C7A37DA4E087_ ._inline-style input[type="text"] { width:150px; }
 #_form_5C7A37DA4E087_ ._inline-style:not(._clear) + ._inline-style:not(._clear) { margin-left:20px; }
 #_form_5C7A37DA4E087_ ._form_element img._form-image { max-width:100%; }
 #_form_5C7A37DA4E087_ ._clear-element { clear:left; }
 #_form_5C7A37DA4E087_ ._full_width { width:100%; }
 #_form_5C7A37DA4E087_ ._form_full_field { display:block; width:100%; margin-bottom:10px; }
 #_form_5C7A37DA4E087_ input[type="text"]._has_error,#_form_5C7A37DA4E087_ textarea._has_error { border:#f37c7b 1px solid; }
 #_form_5C7A37DA4E087_ input[type="checkbox"]._has_error { outline:#f37c7b 1px solid; }
 #_form_5C7A37DA4E087_ ._error { display:block; position:absolute; font-size:13px; z-index:10000001; }
 #_form_5C7A37DA4E087_ ._error._above { padding-bottom:4px; bottom:39px; right:0; }
 #_form_5C7A37DA4E087_ ._error._below { padding-top:4px; top:100%; right:0; }
 #_form_5C7A37DA4E087_ ._error._above ._error-arrow { bottom:0; right:15px; border-left:5px solid transparent; border-right:5px solid transparent; border-top:5px solid #f37c7b; }
 #_form_5C7A37DA4E087_ ._error._below ._error-arrow { top:0; right:15px; border-left:5px solid transparent; border-right:5px solid transparent; border-bottom:5px solid #f37c7b; }
 #_form_5C7A37DA4E087_ ._error-inner { padding:8px 12px; background-color:#f37c7b; font-size:13px; font-family:arial, sans-serif; color:#fff; text-align:center; text-decoration:none; -webkit-border-radius:4px; -moz-border-radius:4px; border-radius:4px; }
 #_form_5C7A37DA4E087_ ._error-inner._form_error { margin-bottom:5px; text-align:left; }
 #_form_5C7A37DA4E087_ ._button-wrapper ._error-inner._form_error { position:static; }
 #_form_5C7A37DA4E087_ ._error-inner._no_arrow { margin-bottom:10px; }
 #_form_5C7A37DA4E087_ ._error-arrow { position:absolute; width:0; height:0; }
 #_form_5C7A37DA4E087_ ._error-html { margin-bottom:10px; }
 .pika-single { z-index:10000001 !important; }
 @media all and (min-width:320px) and (max-width:667px) { ::-webkit-scrollbar { display:none; }
 #_form_5C7A37DA4E087_ { margin:0; width:100%; min-width:100%; max-width:100%; box-sizing:border-box; }
 #_form_5C7A37DA4E087_ * { -webkit-box-sizing:border-box; -moz-box-sizing:border-box; box-sizing:border-box; font-size:1em; }
 #_form_5C7A37DA4E087_ ._form-content { margin:0; width:100%; }
 #_form_5C7A37DA4E087_ ._form-inner { display:block; min-width:100%; }
 #_form_5C7A37DA4E087_ ._form-title,#_form_5C7A37DA4E087_ ._inline-style { margin-top:0; margin-right:0; margin-left:0; }
 #_form_5C7A37DA4E087_ ._form-title { font-size:1.2em; }
 #_form_5C7A37DA4E087_ ._form_element { margin:0 0 20px; padding:0; width:100%; }
 #_form_5C7A37DA4E087_ ._form-element,#_form_5C7A37DA4E087_ ._inline-style,#_form_5C7A37DA4E087_ input[type="text"],#_form_5C7A37DA4E087_ label,#_form_5C7A37DA4E087_ p,#_form_5C7A37DA4E087_ textarea:not(.g-recaptcha-response) { float:none; display:block; width:100%; }
 #_form_5C7A37DA4E087_ ._row._checkbox-radio label { display:inline; }
 #_form_5C7A37DA4E087_ ._row,#_form_5C7A37DA4E087_ p,#_form_5C7A37DA4E087_ label { margin-bottom:0.7em; width:100%; }
 #_form_5C7A37DA4E087_ ._row input[type="checkbox"],#_form_5C7A37DA4E087_ ._row input[type="radio"] { margin:0 !important; vertical-align:middle !important; }
 #_form_5C7A37DA4E087_ ._row input[type="checkbox"] + span label { display:inline; }
 #_form_5C7A37DA4E087_ ._row span label { margin:0 !important; width:initial !important; vertical-align:middle !important; }
 #_form_5C7A37DA4E087_ ._form-image { max-width:100%; height:auto !important; }
 #_form_5C7A37DA4E087_ input[type="text"] { padding-left:10px; padding-right:10px; font-size:16px; line-height:1.3em; -webkit-appearance:none; }
 #_form_5C7A37DA4E087_ input[type="radio"],#_form_5C7A37DA4E087_ input[type="checkbox"] { display:inline-block; width:1.3em; height:1.3em; font-size:1em; margin:0 0.3em 0 0; vertical-align:baseline; }
 #_form_5C7A37DA4E087_ button[type="submit"] { padding:20px; font-size:1.5em; }
 #_form_5C7A37DA4E087_ ._inline-style { margin:20px 0 0 !important; }
 }
 #_form_5C7A37DA4E087_ { position:relative; text-align:left; margin:25px auto 0; padding:20px; -webkit-box-sizing:border-box; -moz-box-sizing:border-box; box-sizing:border-box; *zoom:1; background:#fff !important; border:0px solid #b0b0b0 !important; width:500px; -moz-border-radius:10px !important; -webkit-border-radius:10px !important; border-radius:10px !important; color:#000 !important; }
 #_form_5C7A37DA4E087_ ._form-title { font-size:22px; line-height:22px; font-weight:600; margin-bottom:0; }
 #_form_5C7A37DA4E087_:before,#_form_5C7A37DA4E087_:after { content:" "; display:table; }
 #_form_5C7A37DA4E087_:after { clear:both; }
 #_form_5C7A37DA4E087_._inline-style { width:auto; display:inline-block; }
 #_form_5C7A37DA4E087_._inline-style input[type="text"],#_form_5C7A37DA4E087_._inline-style input[type="date"] { padding:10px 12px; }
 #_form_5C7A37DA4E087_._inline-style button._inline-style { position:relative; top:27px; }
 #_form_5C7A37DA4E087_._inline-style p { margin:0; }
 #_form_5C7A37DA4E087_._inline-style ._button-wrapper { position:relative; margin:27px 12.5px 0 20px; }
 #_form_5C7A37DA4E087_ ._form-thank-you { position:relative; left:0; right:0; text-align:center; font-size:18px; }
 @media all and (min-width:320px) and (max-width:667px) { #_form_5C7A37DA4E087_._inline-form._inline-style ._inline-style._button-wrapper { margin-top:20px !important; margin-left:0 !important; }
 }
​
 #_form_5C7A37DA4E087_ #_form_59BA46D52FB5A_ ._form-thank-you { font-size:28px; left:0; position:relative; right:0; text-align:center; }
</style>
                <%= form_with(model: enquiry, local: true, class: "_form _form_1 _inline-form _dark", id: "_form_5C7A37DA4E087_") do |form| %>

                              
                              <div class="_form-content">
                                <div class="_form_element _x58552419 _full_width _clear">
                                  <div class="_form-title">Ready To Start A Project</div>
                                </div>
                                <div class="_form_element _x40719898 _full_width ">
                                  <label class="_form-label"></label>
                                  <div class="_field-wrapper">
                                    <%= form.text_field :first_name, name: "firstname", placeholder: "First Name",required: "true" %>

                                  </div>
                                </div>
                                <div class="_form_element _x63340275 _full_width ">
                                    <label class="_form-label"></label>
                                  
                                  <div class="_field-wrapper">
                                    <%= form.text_field :last_name, name: "lastname", placeholder: "Last Name"  %>
                                  </div>
                                </div>
                                <div class="_form_element _x59736846 _full_width ">
                                  <label class="_form-label"></label>
                                  <div class="_field-wrapper">
                                    <%= form.text_field :email, name: "email", placeholder: "Your Email",required: "true"  %>
                                    <!--input type="text" name="email" placeholder="Your Email" required="" data-name="email"-->
                                  </div>
                                </div>
                                <div class="_form_element _x07164424 _full_width ">
                                  <label class="_form-label"></label>
                                  <div class="_field-wrapper">
                                    <%= form.text_field :phonenumber, name: "phone", placeholder: "Your Phone Number",required: "true" %>
                                    <!--input type="text" name="phone" placeholder="Your Phone Number" data-name="phone"-->
                                  </div>
                                </div>
                                <div class="_form_element _field1 _full_width ">
                                  <label class="_form-label"></label>
                                  <div class="_field-wrapper">
                                    <%= form.text_field :message , name: "field[1]", placeholder: "Your Message",style:"height: 112px;"%>
                                    <!--textarea name="field[1]" placeholder="Your Message" style="height: 112px;" required="" data-name="your_message"></textarea-->
                                  </div>
                                </div>
                                <div class="_form_element _x38328185 _full_width ">
                                  <label class="_form-label"></label>
                                </div>
                                <div class="_button-wrapper _full_width">
                                  <%= form.submit "Get Started",id: "_form_1_submit",class: "_submit" %>
                                  <!--button id="_form_1_submit" class="_submit" type="submit">Get Started</button-->
                                </div>
                                <div class="_clear-element"></div>
                              </div>
                              <div class="_form-thank-you" style="display:none;"></div>
                             
                              <%end%>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.first_name %></td>
        <td><%= enquiry.last_name %></td>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.phonenumber %></td>
        <td><%= enquiry.message %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @enquiry.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @enquiry.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @enquiry.phonenumber %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>