config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "malibuitlabs.com"
  resources :enquiries, :except => [:index, :edit, :show, :edit, :update, :destroy]
  #get 'pages/index'
  root to: 'pages#index'
  devise_for :users
  resources :blogs, :except => [:latest_blogs]
  get 'latestblogs' => 'blogs#latest_blogs', :as => 'latest_blogs'
  get 'ourblog' => 'blogs#ourblog', :as => 'ourblog'
  get 'about-us' => 'pages#aboutus', :as => 'about-us'
  get 'portfolio' => 'pages#portfolio', :as => 'portfolio'
  get 'services' => 'pages#service', :as => 'services'
  get 'technologies' => 'pages#technologies', :as => 'technologies'
  get 'web-design' => 'pages#webdesign', :as => 'webdesign'
  get 'application-development' => 'pages#application_development', :as => 'application-development'
  get 'bigdata' => 'pages#bigdata', :as => 'bigdata'
  get 'data-warehousing-and-business-intelligence' => 'pages#data-warehousing-and-business-intelligence', :as => 'data-warehousing-and-business-intelligence'
  get 'data-and-information-management' => 'pages#data-and-information-management', :as => 'data-and-information-management'
  get 'cloud-and-infrastructure-service' => 'pages#cloud-and-infrastructure-service', :as => 'cloud-and-infrastructure-service'
  get 'qualityassurance' => 'pages#qualityassurance', :as => 'qualityassurance'
  get 'ecommerce' => 'pages#ecommerce', :as => 'ecommerce'
  get 'cms' => 'pages#cms', :as => 'cms'
  get 'mobile-app-dev' => 'pages#mobile-app-dev', :as => 'mobile-app-dev'
  get 'reactjs' => 'pages#reactjs', :as => 'reactjs'
  get 'nodejs' => 'pages#nodejs', :as => 'nodejs'

 
  #get 'careers' => 'pages#careers', :as => 'careers'
  get 'test' => 'pages#test', :as => 'test'
  get 'ecommerce/shopify' => 'pages#shopify', :as => 'ecommerce/shopify'
  get 'ecommerce/magento' => 'pages#magento', :as => 'ecommerce/magento'
  get 'ecommerce/woocommerce' => 'pages#woocommerce', :as => 'ecommerce/woocommerce'
  get 'ecommerce/upgrademagento' => 'pages#upgrademagento', :as => 'ecommerce/upgrademagento'
  get 'contact' => 'contact_pages#new', :as => 'contact_pages'
  post 'contact' => 'contact_pages#create'
  get 'our-privacy-policy' => 'pages#term&privacy', :as => 'our-privacy-policy'
  get 'careers' => 'careers#new', :as => 'careers'
  post 'careers' => 'careers#create'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_blogsidebar.html.erb
			<% if  %>
				<% if  %>
					<h3><b>Admin Categories</b></h3>
				<% else %>
					<h3><b>Categories</b></h3>
				<% end %>
			<% else %>		
					<h3><b> Categories</b></h3>
			<% end %>			
			<ul class="sidebar-list">
				<% if   %>
					<% if  %>
						<li class="sidebar-item"><%= link_to "Latest Blogs", latest_blogs_path %></li>

					<% end %>
						<li class="sidebar-item"><%= link_to "New Blog", new_blog_path %></li>
				<% end %>

				
				<!--li class="sidebar-item">menu1</li-->
			</ul>

app/views/layouts/_footer.html.erb
			<footer id="colophon" class="site-footer">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-5 col-sm-5">
							<div id="text-3" class="footer-1">
								<div class="textwidget"><img
										src="https://res.cloudinary.com/malibuitlabs/image/upload/v1549601619/mit_png_2_i2byts_fasdnz.png"
										alt="Malibu IT Labs" id="logofoot" ImageHolder="" />
									<div class="more">
										<p class="h">CONNECT WITH US</p>
										<ul>
											<li><a href="tel:+14807457155">+1 (480) 745-7155 <img src="/assets/usa.png" alt="img"
														ImageHolder="/wp-content/themes/TBI/images/usa.png" /> (USA)</a></li>
											<!--li><a href="tel:+919959987477">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="/assets/india.png" alt="img" ImageHolder="/wp-content/themes/TBI/images/india.png" /> (IND)</a></li-->
											<li><a href="mailto:contact@malibuitlabs.com">contact@malibuitlabs.com</a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4">
							<div id="text-4" class="footer-1">
								<div class="textwidget">
									<p class="h">VISIT US</p>
									<ul style="margin-bottom: 11px;">
										
										<li>1250 Borregas Avenue </li>
										<li>Sunnyvale, CA 94089, USA</li>
									</ul>
									<ul>
										
										<li>6991 E Camelback Rd,Suite c310</li>
										<li>Scottsdale, AZ 85251, USA</li>

									</ul>
								</div>
							</div>
						</div>
						<div class="col-md-3 col-sm-3">
							<div id="text-5" class="footer-1">
								<div class="textwidget">
									<p class="h">FOLLOW US</p>
									<ul class="social_icons">
										<li class="icon-first"><a href="/" target="_blank"><i class="fa fa-facebook"
													aria-hidden="true"></i></a> </li>
										<li class="icon-second"><a href="https://twitter.com/it_malibu" target="_blank"><i
													class="fa fa-twitter" aria-hidden="true"></i></a> </li>
										<!--li class="icon-third"><a href="#" ><i class="fa fa-youtube" aria-hidden="true"></i></a> </li-->
										<!--li class="icon-fourth"><a href="#" target="_blank"> </a> </li-->
										<li class="icon-fifth"><a href="https://www.linkedin.com/company/13651015/"
												target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a> </li>
										<!--li class="icon-sixth"><a href="#" ><i class="fa fa-google-plus" aria-hidden="true"></i></a> </li-->
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="row" id="base_footer">
						<div class="col-md-5 col-sm-5">
							<div class="copyright">
								<div id="text-2" class="single-widget other_links myblog-sidebar">
									<div class="widget-body">
										<div class="textwidget">Copyright © 2020 <span> Malibu IT Labs</span> LLC</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4">
							<div class="copyright">
								<div id="text-6" class="other_links">
									<div class="textwidget">
										<ul>

											<li class="terms"><a target="_blank" href="/our-privacy-policy">Terms | Privacy
													Policy </a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-3 col-sm-3">
							<div class="copyright"></div>




						</div>
					</div>
				</div>
			</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'Malibu IT Labs' %></title>
  <meta name="keywords" content="<%= content_for?(:meta_keywords) ? yield(:meta_keywords) : "MalibuItLabs,Malibu IT Labs,MalibuItLabs,malibuitlabs,malibu vizag,vizag malibuitlabs,software companies,software in vizag, visakhapatanam,itsez,andhra"%>"/>
  <meta name="google-site-verification" content="IDeCHUtgCmnYEcMEVIv2a7wlq04K5ZnKjkwyKLvGeQU" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0 ,user-scalable=no "/>
     <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
     <meta name="google" content="nositelinkssearchbox" />
    <meta name="google-site-verification" content="VQnrz1Gf7R9zJseOWoNExGQIcOL1Bne9CZz5NLv5ay0" />
     <meta charset="utf-8" /> 
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <!--link rel='stylesheet' id='bootstrap-min-css-css'  href='/assets/bootstrap.css' type='text/css' media='all' />
            <link rel='stylesheet' id='twentysixteen-style-css'  href='/assets/new-style.css' type='text/css' media='all' />
            <link rel='stylesheet' id='swiper-css-css'  href='/assets/swiper.min.css' type='text/css' media='all' />
            <link rel='stylesheet' id='animate-css-css'  href='/assets/animate.min.css' type='text/css' media='all' />
            <link rel='stylesheet' id='responsive-css-css'  href='/assets/responsive.css' type='text/css' media='all' />
            <link rel='stylesheet' id='normalize-css-css'  href='/assets/normalize.css' type='text/css' media='all' /-->
             <%= stylesheet_link_tag "bootstrap.css" %>
               <%= stylesheet_link_tag "swiper.min.css" %>
                <%= stylesheet_link_tag "responsive.css" %>
                 <%= stylesheet_link_tag "normalize.css" %>
                  <%= stylesheet_link_tag "new-style.css" %>
                   <%= stylesheet_link_tag "main.min.css" %>
                    <%= stylesheet_link_tag "js_composer.min.css" %>
                     <%= stylesheet_link_tag "font-awesome.min.css" %>
                      <%= stylesheet_link_tag "animate.min.css" %>
                      
            <link rel='stylesheet' id='js_composer_front-css'  href='/assets/js_composer.min.css' type='text/css' media='all' />
            <link rel="icon" href="https://res.cloudinary.com/malibuitlabs/image/upload/s--rXud4zOr--/q_jpegmini/v1549601619/mit_png_2_i2byts_fasdnz.png" sizes="32x32" />
            <link rel="icon" href="https://res.cloudinary.com/malibuitlabs/image/upload/s--rXud4zOr--/q_jpegmini/v1549601619/mit_png_2_i2byts_fasdnz.png" sizes="192x192" />
            <link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.malibuitlabs.com" />
            <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="www.malibuitlabs.com" /> 
            <meta name="generator" content="WordPress 4.6.11" />
            <link rel="alternate" type="application/json+oembed" href="https://www.malibuitlabs.com" />
            <link rel="alternate" type="text/xml+oembed" href="www.malibuitlabs.com" />

            <style type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style>
            <meta name="generator" content="" />
          <link href="https://fonts.googleapis.com/css?family=Montserrat|Titillium+Web:600" rel="stylesheet">
          <noscript><style type="text/css"> .wpb_animate_when_almost_visible { opacity: 1; }</style></noscript> 
         
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
          <script>
          	var isMobile = window.orientation > -1;
            
           

          </script>
 <!-- Google Tag Manager -->
 <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-83241788-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-83241788-1');
</script>     
<!-- End Google Tag Manager -->
  </head>

  <body>
     
            <%= render 'layouts/navbar'%>
          
              
            
    
          <%= yield %>
      
     <%= render 'layouts/footer'%>
      <%= javascript_include_tag "jquery.flip.min.js" %>
   
        <%= javascript_include_tag "jquery.multilevelpushmenu.min.js" %>
        
          <%= javascript_include_tag "main.min.js" %>
           <%= javascript_include_tag "mlpushmenu.js" %>
            <%= javascript_include_tag "modernizr.custom.js" %>
             <%= javascript_include_tag "modernizr.js" %> 
            
            <%= javascript_include_tag "myflip.js" %>
             <%= javascript_include_tag "owl.carousel.js" %>
               
            <%= javascript_include_tag "picturefill.min.js" %>
             <%= javascript_include_tag "TweenMax.min.js" %>
               
      
    <!--script src="/assets/jquery.js"></script-->
        <%= javascript_include_tag "jquery.js" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!--script src="/assets/bootstrap.js"></script-->
     <%= javascript_include_tag "bootstrap.js" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
   <!--script type='text/javascript' src='/assets/swiper.jquery.min.js'></script-->
    <%= javascript_include_tag "swiper.jquery.min.js" %>
<!--script type="text/javascript" src="/assets/wp-embed.min.js"></script-->

   <!--script type="text/javascript" src="/assets/js_composer_front.min.js"></script-->
  <%= javascript_include_tag "js_composer_front.min.js" %>
<!--script data-cfasync="false" src="/assets/jquery-1.10.2.min.js"></script-->
<!--script  src="/assets/jquery.flip.min.js"></script-->
 <%= javascript_include_tag "jquery.flip.min.js" %>

<!--script  src="/assets/myflip.js"></script>
       
                <!--new---slider-end-->
      <!-- .site-inner -->  
      
            </div>
          </div><!-- .site -->
<script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/5c6159e16cb1ff3c14cbf532/default';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
 
<script type="text/javascript">
(function(url){
  if(/(?:Chrome\/26\.0\.1410\.63 Safari\/537\.31|WordfenceTestMonBot)/.test(navigator.userAgent)){ return; }
  var addEvent = function(evt, handler) {
    if (window.addEventListener) {
      document.addEventListener(evt, handler, false);
    } else if (window.attachEvent) {
      document.attachEvent('on' + evt, handler);
    }
  };
  var removeEvent = function(evt, handler) {
    if (window.removeEventListener) {
      document.removeEventListener(evt, handler, false);
    } else if (window.detachEvent) {
      document.detachEvent('on' + evt, handler);
    }
  };
  var evts = 'contextmenu dblclick drag dragend dragenter dragleave dragover dragstart drop keydown keypress keyup mousedown mousemove mouseout mouseover mouseup mousewheel scroll'.split(' ');
  var logHuman = function() {
    var wfscr = document.createElement('script');
    wfscr.type = 'text/javascript';
    wfscr.async = true;
    wfscr.src = url + '&r=' + Math.random();
    (document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(wfscr);
    for (var i = 0; i < evts.length; i++) {
      removeEvent(evts[i], logHuman);
    }
  };
  for (var i = 0; i < evts.length; i++) {
    addEvent(evts[i], logHuman);
  }
})('//');
</script> 

<script type="text/javascript">

$(document).ready(function(){
  var newURl = window.location.href;
  console.log(newURl);
  $( ".page_url" ).val(newURl);
  var pageTitle = $('.banner_text_inner h1').text();
  $( ".page_title" ).val(pageTitle);
});
</script>


    <script type="text/javascript">
      jQuery("#logofoot").mouseover(function(){jQuery(this).attr("src","https://res.cloudinary.com/malibuitlabs/image/upload/v1549601619/mit_png_2_i2byts_fasdnz.png")}),jQuery("#logofoot").mouseout(function(){jQuery(this).attr("src","https://res.cloudinary.com/malibuitlabs/image/upload/v1549601619/mit_png_2_i2byts_fasdnz.png")});
    
/*
                 jQuery(".home .navigation").removeClass("nav_white");
            jQuery(window).scroll(function(){var n=jQuery(window).scrollTop();n>=1?jQuery(".home .navigation").addClass("nav_white"):jQuery(".home .navigation").removeClass("nav_white")}),jQuery("body").click(function(){jQuery(".wpcf7-response-output").css("display","none").fadeOut(500)});*/

         
      
    jQuery(".footer_fix_info a").click(function(){var o=jQuery(".footer_fix_info").css("bottom");"0px"==o?(jQuery(".footer_fix_info").animate({bottom:"-120px"},200),jQuery(".footer_fix_info .fa.fa-angle-down").css("transform","rotate(-180deg)")):(jQuery(".footer_fix_info").animate({bottom:"0px"},200),jQuery(".footer_fix_info .fa.fa-angle-down").css("transform","rotate(0deg)"))});
    
    
    jQuery(document).on('click','.ddd',function(event) {
  event.preventDefault();
 $('html,body').animate( { scrollTop:$(this.hash).offset().top -46 } , 2000);
  } ); 
  
  </script>

</body>
<!--Start of Tawk.to Script (0.3.2)-->

</html>